### ISSUE TITLE
UnexpectedEndOfStream exception when downloading and uploading files

### ISSUE THREAD

**Issue by gpanshu** [aws/aws-sdk-kotlin#960]
### Describe the bug

When we upload 50 files as part of integration tests and then immediately download 50 files we see an end of stream error

06-19 13:47:46.107 17791 19872 E AndroidRuntime: Caused by: java.lang.Exception: aws.smithy.kotlin.runtime.http.HttpException: java.io.IOException: unexpected end of stream on https:.../...
06-19 13:47:46.107 17791 19872 E AndroidRuntime: 	at com.amplifyframework.storage.s3.transfer.worker.BaseTransferWorker.doWork$suspendImpl(BaseTransferWorker.kt:119)

### Expected behavior

IOException should not arise when you are trying to download a large amount of files.

### Current behavior

aws.smithy.kotlin.runtime.http.HttpException: java.io.IOException

One thing I have noticed is that if I remove the upload task from the setup and put it inside the actual test case this issue does not arise. (potentially something to do with the delay after upload that the download starts)

### Steps to Reproduce

1. Create an integration test suite
2. Upload 50 small files in the setup once method
3. Download the same 50 small files in the test case (it fails after the 5 try and sometimes after the 9th try)

Code can be found here : https://github.com/aws-amplify/amplify-android/blob/e824356ef187a7a43f509116acda58a8767cf35c/aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/StorageStressTest.kt#L41

### AWS Kotlin SDK version used

0.27.0-beta

### Platform (JVM/JS/Native)

Native

### Operating System and version

Android Pixel 5 API 32

**Comment by ianbotsf** [comment]
I cannot reproduce the issue with the steps given (create a test, upload 50 files in setup method, download 50 files in test case). The linked code is also not very helpful because it doesn't reference any classes/methods from the AWS SDK for Kotlin (e.g., there's no S3 client, no `putObject`/`getObject` calls, etc.). I'm guessing they're called behind various abstractions but they're not apparent from a quick read.

Can you provide a minimal example of this?
